# Generated by Django 4.1.4 on 2022-12-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='No description', max_length=500),
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
