# Generated by Django 4.1.4 on 2022-12-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_description_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='catagory',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
