ARCH := $(shell uname -m)

ifeq ($(ARCH), aarch64)
    CXX = g++
else
#     CXX = g++ -m64
    CXX = g++
endif

CXXFLAGS=-I. -I../common -I../tests -Iobjs/ -O3 -std=c++11 -g -Wall

APP_NAME=runtasks
OBJDIR=objs
COMMONDIR=../common

PPM_CXX=$(COMMONDIR)/ppm.cpp
PPM_OBJ=$(addprefix $(OBJDIR)/, $(subst $(COMMONDIR)/,, $(PPM_CXX:.cpp=.o)))

default: $(APP_NAME)

.PHONY: dirs clean

dirs:
	if not exist $(OBJDIR) mkdir $(OBJDIR)

clean:
	del /q $(OBJDIR) *.ppm *~ $(APP_NAME)

OBJS=$(PPM_OBJ) $(OBJDIR)/tasksys.o

$(APP_NAME): clean dirs $(OBJS)
	$(CXX) ../tests/main.cpp $(CXXFLAGS) -o $@ $(OBJDIR)/tasksys.o -lm -lpthread

$(OBJDIR)/%.o: $(COMMONDIR)/%.cpp
	$(CXX) $< $(CXXFLAGS) -c -o $@

$(OBJDIR)/%.o: %.cpp
	$(CXX) $< $(CXXFLAGS) -c -o $@
